### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, 'v'.

### ISSUE THREAD

**Issue by Hong-yu1999** [hachinoone/DRLSolver4DTSP#1]
Hello,I have a problem with the command “python m2/train.py --baseline rollout --graph_size 19”.Can you help me?
Traceback (most recent call last):
  File "m2/train.py", line 499, in <module>
    run(get_options())
  File "m2/train.py", line 414, in run
    checkpoint2 = torch.load('m2/T2V_normal_19.pt')
  File "D:\anaconda\envs\py37\lib\site-packages\torch\serialization.py", line 608, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "D:\anaconda\envs\py37\lib\site-packages\torch\serialization.py", line 777, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, 'v'.

**Comment by hachinoone** [comment]
Thank you for your question.
The former pretrained model T2V have some errors while uploading to the github for some reasons I don't know. And I have not checked the file after uploading. Sorry about that.
Now, the T2V is re-uploaded, and the problem will be fixed. Thanks.

**Comment by Hong-yu1999** [comment]
I'm sorry to bother you again. The problem was solved just now, but when running any command in "Quick Start", it often reported an error
Traceback (most recent call last):
   File "/home/zhanghy/DRLSolver4DTSP/m2/train.py", line 9, in <module>
     from transformer import AttentionModel,AttentionModel2
   File "/home/zhanghy/DRLSolver4DTSP/m2/transformer.py", line 264, in <module>
     class StateTSP(NamedTuple):
RuntimeError: __class__ not set defining 'StateTSP' as <class 'transformer.StateTSP'>. Was __classcell__ propagated to type.__new__?

**Comment by hachinoone** [comment]
I have not met this error before. I have googled this error, and there is a similar problem in this website: https://stackoverflow.com/questions/64203107/django-problem-runtimeerror-class-not-set-defining-abstractbaseuser-as. I guess maybe it is because of your python verision is 3.7. Could you please downgrade your python version to 3.6.3 and try again?

**Comment by Hong-yu1999** [comment]
Unfortunately, the problem seems to still exist. I create a project in local pycharm without an error occasionally, but every time I run the code on the lab server, I get an error

**Comment by hachinoone** [comment]
I ran this project on my lab server again, and no errors are found. I suggest you can delete the whole project in your server, re-clone this project (just in order to clear the cache), and then try to run with python=3.6.3 and pytorch=1.7. Thanks.

**Comment by Hong-yu1999** [comment]
Problem solved, thanks

**Comment by Unstoppable231** [comment]
请问是如何解决的？

**Comment by hachinoone** [comment]
> 请问是如何解决的？

可以试试看先把缓存清理一下（__pycache__文件夹），再用python=3.6.3 和 pytorch=1.7的环境跑
